config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'streams/index'
  end

  get 'admin/index'

  # get 'pages/index'
  # post '/contact', to: 'pages#contact'
  # match '*path', to: 'pages#index', via: :all
  root 'pages#index'
  get 'twitch', to: 'pages#index'
  get 'youtube', to: 'pages#index'
  get 'twitch_streams', to: 'pages#twitch_streams'
  get 'youtube_streams', to: 'pages#youtube_streams'


  get 'admin', to: 'admin#index'
  namespace :admin do
    resources :streams
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/admin/streams_controller.rb
# frozen_string_literal: true
class Admin::StreamsController < AdminController

  def index
    @streams = Stream.all
  end

  def show
    @stream = Stream.find(params[:id]) rescue nil
  end

  def edit
    @stream = Stream.find(params[:id]) rescue nil
  end

  def update

    begin
      @stream = Stream.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      @streams = Stream.all
      render :index
    end

    @stream.name = params['name']
    @stream.url = params['url']
    @stream.type_platform = params['type_platform']
    @stream.show = params['show']

    if @stream.save
      @stream = Stream.find(params[:id]) rescue nil
      render :edit
    end
  end

  def new; end

  def create

    @stream = Stream.new
    @stream.name = params['name']
    @stream.url = params['url']
    @stream.type_platform = params['type_platform']
    @stream.show = params['show']

    if @stream.save
      @stream = Stream.find(@stream.id) rescue nil
      render :edit
    else
      render :new
    end
  end
  
  def destroy
    @stream = Stream.destroy(params[:id])

    if @stream.delete
      @streams = Stream.all
      render :index
    else
      render :new
    end
  end



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  # layout 'admin'
  # before_filter :require_login
  #
  # private
  # def not_authenticated
  #   redirect_to login_path, alert: "Please login first"
  # end


  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def twitch_streams
    @streams = Stream.where(type_platform: 'twitch').where(show: true)
    render json: { data: @streams }
  end

  def youtube_streams
    @streams = Stream.where(type_platform: 'youtube').where(show: true)
    render json: { data: @streams }
  end
end

app/helpers/admin/streams_helper.rb
module Admin::StreamsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style=" margin-left: 100px; margin-top: 100px;">
<h1>Admin page</h1>
<p>In this page you can change data tables</p>
<button><%= link_to "Streams", admin_streams_path %></button>

app/views/admin/streams/edit.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style=" margin-left: 100px; margin-top: 100px;">
<% if @stream -%>
<h1>Edit Stream</h1>
<%= form_tag "/admin/streams/" + @stream.id.to_s, :method => 'PUT' do %>
  <p>
    <strong style="margin-right: 80px;">Name</strong>
    <%= text_field_tag :name , @stream.name,:required => true %>
  </p>
  <p>
    <strong style="margin-right: 85px;">URL</strong>
    <%= text_field_tag :url,  @stream.url,:required => true %>
  </p>
  <p>
    <strong style="margin-right: 20px;">Type platform</strong>
    <%= select_tag :type_platform, options_for_select(['twitch','youtube'],@stream.type_platform)  %>
  </p>
  <p>
    <strong  style="margin-right: 80px;">Show</strong>
    <%= check_box_tag("show",@stream.show,@stream.show) %>
    <%#= check_box("show", "accepted", {}, true, false) %>
  </p>
  <%= submit_tag("Save") %>
<% end %>
<button><%= link_to "To all", admin_streams_path %></button>
<% else -%>
  <h1>Stream not found.</h1>
  <button><%= link_to "Go To All", admin_streams_path %></button>
<% end %>
</body>
</html>

app/views/admin/streams/index.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style=" margin-left: 100px; margin-top: 100px;">
<h1>Listing Streams</h1>
<p style="margin: 10px">
    <button><%= link_to "New stream", new_admin_stream_path %></button>
</p>
<table>
  <% if @streams -%>
  <thead>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Type platform</th>
    <th>Show</th>
  </tr>
  </thead>
  <tbody>
  <% @streams.each do |stream| %>
    <tr>
      <td><%= stream.name %></td>
      <td><%= stream.url %></td>
      <td><%= stream.type_platform %></td>
      <td><%= stream.show ? 'true' : 'false' %></td>
      <td><button><%= link_to "Show", admin_stream_path(stream) %></button></td>
      <td><button><%= link_to "Edit", edit_admin_stream_path(stream) %></button></td>
      <td><button><%= link_to "Delete", "/admin/streams/" + stream.id.to_s, method: :delete, data: { confirm: "Are you sure?" } %></button></td>
    </tr>
  <% end %>
  </tbody>
  <% end -%>
</table>
</body>
</html>

app/views/admin/streams/new.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style=" margin-left: 100px; margin-top: 100px;">
<h1>Show Stream</h1>
<%= form_tag "/admin/streams/", :method => 'POST' do %>

<p>
  <strong style="margin-right: 80px;">Name</strong>
  <%= text_field_tag :name, params[:name],:required => true %>
</p>
<p>
  <strong style="margin-right: 85px;">URL</strong>
  <%= text_field_tag :url, params[:url],:required => true %>
</p>
<p>
  <strong style="margin-right: 20px;">Type platform</strong>
  <%= select_tag :type_platform, raw("<option value='twitch'>Twitch</option><option value='youtube'>Youtube</option>") %>
</p>
<p>
  <strong  style="margin-right: 80px;">Show</strong>
  <%= check_box_tag("show") %>
  <%#= check_box("show", "accepted", {}, true, false) %>
</p>
  <%= submit_tag("Save") %>
<% end %>

<button><%= link_to "To all", admin_streams_path %></button>
</body>
</html>

app/views/admin/streams/show.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body style=" margin-left: 100px; margin-top: 100px;">
<% if @stream -%>
<h1>Show Stream</h1>
<p>
  <strong>Name</strong>
  <span><%= @stream.name %></span>
</p>
<p>
  <strong>URL</strong>
  <span><%= @stream.url %></span>
</p>
<p>
  <strong>Type platform</strong>
  <span><%= @stream.type_platform %></span>
</p>
<p>
  <strong>Show</strong>
  <span style=""><%= @stream.show ? 'true' : 'false' %></span>
</p>
<p>
  <button><%= link_to "Edit", edit_admin_stream_path(@stream) %></button>
</p>

<button><%= link_to "To all", admin_streams_path %></button>
<% else -%>
  <h1>Stream not found.</h1>
  <button><%= link_to "Go To All", admin_streams_path %></button>
<% end -%>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestReactApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<!--<h1>Pages#index</h1>-->
<!--<p>Find me in app/views/pages/index.html.erb</p>-->


<%= javascript_pack_tag 'index' %>

<%#= javascript_pack_tag 'hello_react' %>

<%#= react_component('Hello', name: 'Icicle') %>

<%#= react_component('GreetUser', name: 'Icicle') %>

<!-- becomes: -->
<!--<div data-react-class="GreetUser" data-react-props="{&quot;name&quot;:&quot;Icicle&quot;}"></div>-->